app = "hello-fiddle"
primary_region = "ewr"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[build.args]
  HYPERFIDDLE_DOMAIN="hello-fiddle"


# NO_COLOR=1 fly deploy --config src/hello_fiddle/fly.toml --remote-only --build-only --build-arg ELECTRIC_USER_VERSION=$(git describe --tags --long --always --dirty)
# fly scale vm shared-cpu-8x --config src/hello_fiddle/fly.toml
# fly scale show  --config src/hello_fiddle/fly.toml
# fly status --config src/hello_fiddle/fly.toml